### ISSUE TITLE
change to extract for polygons instead of points

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/nlcd#1]
right now, we only support extracting for points; we should also support `addNlcdData::get_nlcd_data_point_buffer()` with a default of 400 m, but with a degauss argument to change this

**Comment by cole-brokamp** [comment]
and make sure that specifying a buffer size of 0 is supported for just points (make sure this doesn't error R code and single pixel metrics that are converted to percentages still work ok)

**Comment by erikarasnick** [comment]
`addNlcdData::get_nlcd_data_point_buffer()` uses `sf::st_buffer()` to create buffers around points. `st_buffer()` errors when the buffer radius is zero. Right now, I have written code in the container such that if `buffer_radius` is zero, it will use `addNlcdData::get_nlcd_data()` which is what we've been using in the container for points. If `buffer_radius` is anything other than zero, it uses `addNlcdData::get_nlcd_data_point_buffer()`, with a default of 400 m. 

This results in slightly different output as noted in the addNlcdData [readme](https://github.com/geomarker-io/addNlcdData). Do you think this is okay, as long as we describe it in the `optional argument` section of the `nlcd` readme? Or should we go back and change the code in the `addNlcdData` package?

**Comment by cole-brokamp** [comment]
Let's assume that anyone who actually wants to use for points (buffer of 0) will have a specific technical need where they can go and use {addNlcdData} instead of a DeGAUSS container.

For the container, let's make it *always* compute for a buffer radius and only allow returning columns that would match that.  We can use a default buffer radius of 400 m and make changing the buffer radii an optional argument.
