### ISSUE TITLE
Workaround for Pulling fst Files?

### ISSUE THREAD

**Issue by osageorange** [degauss-org/nlcd#7]
I'm attempting to use this tool in a highly secure compute environment with extremely limited network access, which appears to prevent pulling the fst files from the repository in the following lines (59-60) from https://github.com/geomarker-io/addNlcdData/blob/master/R/nlcd_data_functions.R

```
s3_uri <- glue::glue("s3://geomarker/nlcd/nlcd_fst/nlcd_chunk_{nlcd_chunk}.fst")
nlcd_file <- s3::s3_get(s3_uri, public = T, quiet = [TRUE](https://rdrr.io/r/base/logical.html))
```

Is there a workaround available? Potentially including the fst files within the container?

**Comment by erikarasnick** [comment]
The fst files total about 48GB, which is too large to include in the container. One solution could be to download all the fst files and storing them in the secure environment before running the container. If they are stored at a specific file path within the environment, the container will recognize that the files are already there and would skip the download.

**Comment by osageorange** [comment]
Ok thanks, I will work with the system admins to find a way to download the files to ./nlcd_fst/ before running the container.

**Comment by erikarasnick** [comment]
Awesome! I think the path will have to be `./s3_downloads/geomarker/nlcd/nlcd_fst` for the container to recognize. Kind of long, but an artifact of how we do automated downloads from s3.

**Comment by osageorange** [comment]
Thank you, that's helpful!
