### ISSUE TITLE
why the nlcd of geocoded_v3.0.2 is so slow?

### ISSUE THREAD

**Issue by HuipingVUMC** [degauss-org/nlcd#9]
I am using degauss geocoded v3.0.2. Loop through deep_index, roads, adapt, greespace all fast enough for 10000 rows input data. On the process I can see the Container CPU used close to 105%/2000%. Why it used so small size resources and so slow on nlcd? Any way I can speed up this step? Thanks. Huiping
![Screenshot 2024-09-24 at 3 17 44 PM](https://github.com/user-attachments/assets/d1b81b4e-334e-4076-8de1-18a92bc7ef29)

**Comment by cole-brokamp** [comment]
The code here: https://github.com/degauss-org/nlcd is used in this container to link to files an order of magnitude larger than those in the other containers you mention.

Urban imperviousness relies on smaller files and is much faster, but there is no DeGAUSS container for it.  You can see an example of how we do this in R here: https://github.com/geomarker-io/appc/blob/main/inst/urban_imperviousness.R

**Comment by HuipingVUMC** [comment]
Thank you so much professor Brokamp to give this so fast help!!

Huiping
________________________________
